# CHA LightDM GTK greeter (XFCE Edition)
[greeter]
theme-name = CHA
icon-theme-name = Papirus-CHA
cursor-theme-name = Bibata-Modern-Classic
font-name = Inter 11
background = /usr/share/backgrounds/cha/01-abyss-teal-1920.png
user-background = false
indicators = ~host;~spacer;~clock;~spacer;~session;~a11y;~language;~power
clock-format = %H:%M
position = 50%,center 55%,center
default-user-image = /usr/share/icons/Papirus-CHA/64x64/apps/cha-user.svg
panel-position = bottom
